### ISSUE TITLE
std.experimental.allocator.common.Ternary conflicts with std.typecons.Ternary in recent build

### ISSUE THREAD

**Issue by zachthemystic** [dlang-community/dfmt#277] opened 2017-05-10 00:28 UTC
`dub fetch dfmt` then `dub run dfmt` on my mac yields this error which was already fixed in dscanner:

.dub/packages/experimental_allocator-2.70.0-b1/experimental_allocator/src/std/experimental/allocator/package.d(322,13): Error: std.experimental.allocator.common.Ternary at .dub/packages/experimental_allocator-2.70.0-b1/experimental_allocator/src/std/experimental/allocator/common.d(14,1) conflicts with std.typecons.Ternary at /usr/local/Cellar/dmd/2.074.0/include/dlang/dmd/std/typecons.d(7658,1)

**Comment by BBasile** [comment] 2017-05-10 00:33
To fix the issue

- delete `dfmt-0.4.5` from the local DUB registry.
- run `dub fetch dfmt --version=0.5.0-beta.5`
- run `dub run dfmt`

The problem is that DUB fetches the latest stable release. Betas are not considered as release so a very old version is build which used a Ternary coming from a user package. Now Ternary is in std.

The problem will be fixed when dfmt 0.5.0 will be released.

**Comment by wilzbach** [comment] 2017-05-10 10:38
FWIW `dub run` doesn't do a fetch at all (or even queries the dub registry), it uses the latest locally available version.

**Comment by BBasile** [comment] 2017-05-10 10:41
I think he ran `dub fetch dfmt` in a first time. This command takes latest tag, excluding betas and alphas.

**Comment by wilzbach** [comment] 2017-05-10 11:13
>  This command takes latest tag, excluding betas and alphas.

I know, I was just trying to point this out as another potential source for errors for others finding this thread - I should have stated this more clearly, sorry.

**Comment by BBasile** [comment] 2017-05-10 11:23
@wilzbach, good point. I've edited the report. It's time to use our power now that we can do more ;)

**Comment by zachthemystic** [comment] 2017-05-10 17:54
I got past that issue, but now I have a wall of linker errors. But it's a different bug. File it? Or is it just me:
$ dub run --force dfmt
Building package dfmt in /Users/zach/.dub/packages/dfmt-0.5.0-beta.5/dfmt/
Performing "debug" build using dmd for x86_64.
libdparse 0.7.0: building configuration "library"...
dfmt 0.5.0-beta.5: building configuration "application"...
Linking...
ld: warning: pointer not aligned at address 0x10020EE75 (_D4dfmt8ast_info13FormatVisitor6__initZ + 0 from .dub/packages/dfmt-0.5.0-beta.5/dfmt/.dub/build/application-debug-posix.osx-x86_64-dmd_2074-F5B2F873AC8C7E7FE12FEB27FF7FC08A/dfmt.o)
ld: warning: pointer not aligned at address 0x10020EEA5......
...... goes on for about 100 screens.

**Comment by BBasile** [comment] 2017-05-11 03:43
Yeah it's another this, the problem is known https://issues.dlang.org/show_bug.cgi?id=17289

**Comment by WebFreak001** [comment] 2020-03-09 12:39
external issue resolved fixed, initial issue stale and probably fixed (consider commenting to reopen)

**Closed by WebFreak001** 2020-03-09 12:39 UTC
