### ISSUE TITLE
structure initializer doesn't look nice

### ISSUE THREAD

**Issue by andre2007** [dlang-community/dfmt#350] opened 2018-04-10 19:15 UTC
my structure initializer coding I would like to be formatted s.th. like this:
```
UpdateItemInput updateItemInput = {
    key: ["AppId":appIdKey],
    updateExpression: "set SparkApplicationId = :i, ProcessState=:s, RequestedState=:r, UpdatedAt=:t",
    expressionAttributeValues: [
        ":i": sparkAppIdKey,
        ":s": processStateKey,
        ":r": requestedStateKey,
        ":t": updatedAtKey
    ],
    returnValues:"UPDATED_NEW"
};
```

but after dfmt execution it looks like this:
```
UpdateItemInput updateItemInput = {
key:
    ["AppId" : appIdKey], updateExpression
        : "set SparkApplicationId = :i, ProcessState=:s, RequestedState=:r, UpdatedAt=:t",
expressionAttributeValues : [
        ":i" : sparkAppIdKey, ":s" : processStateKey, ":r"
        : requestedStateKey, ":t" : updatedAtKey], returnValues : "UPDATED_NEW"
};
```

**Comment by WebFreak001** [comment] 2018-04-11 12:17
duplicate of #256, which is a partial duplicate of #254

**Closed by WebFreak001** 2018-04-11 12:17 UTC
