### ISSUE TITLE
Remove dependency for rdmd in dub package

### ISSUE THREAD

**Issue by skyline131313** [dlang-community/dfmt#546] opened 2022-02-12 17:29 UTC
serve-d doesn't compile because of this, there is no rdmd for ARM as dmd doesn't have an ARM target.

https://github.com/dlang-community/dfmt/blob/master/dub.json#L18

**Comment by WebFreak001** [comment] 2022-02-12 17:30
duplicate of #472

**Closed by WebFreak001** 2022-02-12 17:31 UTC
